description: basic config with default colors and building representation
name: Complete View of Vertx City
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
    edges:
      - name: API
        color: "#000000"
    outlines: null
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: INSTANTIATE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - INSTANTIATE
hierarchy_links:
  - INSTANTIATE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - io.vertx.core.TimeoutStream
  - io.vertx.core.spi.cluster.RegistrationUpdateEvent
  - io.vertx.core.cli.UsageMessageFormatter
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: ""
  crack: ""
orientation: OUT
default_level: 4
camera_data:
  alpha: 2.8013019237882317
  beta: 0.7023001512419031
  radius: 29.559067943185145
  target:
    x: 11.684349326346426
    y: 8.721032203281815
    z: 10.633651660390944
metrics:
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
projectId: vert.x
clones:
  map: {}
