# config file for varicity
# you may alter this file before running the program
# pick your color at https://htmlcolorcodes.com/ 

building:
  colors:
    outline: "#145a32" # dark green
    edges: "#a569bd" # light purple
    faces: # ordered by importance, descending : in case of conflict, the first color to match will be displayed
      - name: "STRATEGY"
        color: "#2c3e50" # dark grey
      - name: "FACTORY"
        color: "#7d3c98" # purple
      - name: "INTERFACE"
        color: "#e67e22" # orange
      - name: "CLASS"
        color: "#2e86c1" # light blue
district:
  colors:
    outline: "#145a32" # dark green
    edges: "#a569bd" # light purple
    faces:
      - name: "PACKAGE"
        color: "#6e2c00" # light yellow
