# config file for varicity
# you may alter this file before running the program
# pick your color at https://htmlcolorcodes.com/ 

building:
  colors:
    # outline: "#145a32" # dark green
    # edges: "#a569bd" # light purple
    faces: # ordered by importance, descending : in case of conflict, the first color to match will be displayed
      - name: "!HOTSPOT"
        color: "#555555"
      - name: "VP"
        color: "#FF6F33"
      - name: "STRATEGY"
        color: "#17202a" # black
      - name: "FACTORY"
        color: "#7d3c98" # purple
      - name: "INTERFACE"
        color: "#e67e22" # orange
      - name: "ABSTRACT"
        color: "#2c3e50" # dark blue
      - name: "CLASS"
        color: "#335DFF"

    outlines:
#      - name: "API"
#        color: "#FF0000"
      # - name: "CLASS"
        # color: "#000000"

district:
  colors:
    # outline: "#145a32" # dark green
    # edges: "#a569bd" # light purple
    faces:
      - name: "PACKAGE"
        color: "#801A2E"
      - name: "VP"
        color: "#1A8039"

link:
  colors:
    - name: "IMPLEMENTS"
      color: "#e67e22"
    - name: "EXTENDS"
      color: "#2e86c1"
    - name: "DUPLICATES"
      color: "#2B914A"

blacklist: #all classes that must not appear
  - "org.jfree.chart.util.PublicCloneable"
  # - "org.jfree.chart.renderer.AbstractRenderer"

api_classes: #all API classes
  - "org.jfree.chart.JFreeChart"