version: "3.6"

services:
  symfinder:
    build:
      context: .
      dockerfile: docker/symfinder/SymfinderDockerfile
    image: symfinder
    container_name: symfinder
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./resources:/resources
      - ./generated_visualizations:/generated_visualizations
      - ./d3:/d3
    depends_on:
      - neo4j
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre
      - SYMFINDER_UID=${SYMFINDER_UID}
      - SYMFINDER_GID=${SYMFINDER_GID}
      - SOURCES_PACKAGE=${SOURCES_PACKAGE}
      - GRAPH_OUTPUT_PATH=${GRAPH_OUTPUT_PATH}
      - PROJECT_NAME=${PROJECT_NAME}

  neo4j:
    image: neo4j:3.5.0
    container_name: symfinder-neo4j
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/root
