version: "3.6"

services:
  symtest:
    build:
      context: .
      dockerfile: docker/symtest/SymtestDockerfile
    image: symtest
    container_name: symtest
    ports:
      - "127.0.0.1:8080:8080"
    tmpfs:
      - /resources
    volumes:
      - ./generated_test_visualizations:/generated__test_visualizations
    depends_on:
      - neo4j
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre
      - MAVEN_CONFIG=/var/maven/.m2
#    user: ${SYMFINDER_UID}:${SYMFINDER_GID}

  neo4j:
    image: neo4j:3.5.0
    container_name: symfinder-neo4j
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    tmpfs:
      - /data
    environment:
      - NEO4J_AUTH=neo4j/root
#      - NEO4J_dbms_memory_pagecache_size=64G
