description: basic config with default colors and building representation
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
    edges:
      - name: API
        color: "#000000"
    outlines: null
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: INSTANTIATE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - INSTANTIATE
hierarchy_links:
  - INSTANTIATE
  - IMPLEMENTS
  - EXTENDS
blacklist:
  - org.jfree.chart.util.PublicCloneable
  - org.jfree.chart.event
  - org.jfree.data.general
api_classes:
  - fr.unice.polytech.si3.qgl.stormbreakers.data.objective.Goal
  - fr.unice.polytech.si3.qgl.stormbreakers.math.Surface
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
orientation: OUT
default_level: 4
camera_data:
  alpha: 0.167451519847481
  beta: 0.7842601589237435
  radius: 29.559067943185145
  target:
    x: 11.684349326346426
    y: 8.721032203281815
    z: 10.633651660390944
projectId: regatta
