version: "3.6"
services:
   
 varicitybackend:
    image: deathstar3/varicity-backend:${TAG}
    container_name: varicity-backend
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    volumes:
      - ${VOLUME_PATH}:/persistent:rw
    environment:
      - PERSISTENT_DIR=/persistent
      - SYMFINDER_DIR=/persistent/data/symfinder_files
      - METRICS_DIR=/persistent/data/symfinder_files/externals
      - PARSED_INPUT_DIR=/persistent/data/symfinder_files/parsed
      - DATABASE_PATH=/persistent/varicitydb
      - VISUALISATION_CONFIGS_PATH=/persistent/configs
      - DEFAULT_CONFIGS_DIR=/default-configs
