description: basic config with default colors and building representation
name: AzureusCoreComponent
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
      - name: API
      - name: VARIANT
      - name: TEMPLATE
      - name: DECORATOR
      - name: COMPOSITION_STRATEGY
      - name: METHOD_LEVEL_VP
      - name: DENSE
      - name: PUBLIC
      - name: PRIVATE
    edges:
      - name: API
        color: "#000000"
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - com.aelitis.azureus.core.AzureusCoreComponent
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: ""
  crack: ""
orientation: OUT
default_level: 4
camera_data:
  alpha: 0.5790674045099465
  beta: 1.0361910251039217
  radius: 52.34092353191997
  target:
    x: 20.324228614333016
    y: -2.0413720878009567
    z: 18.741930974585234
metrics:
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
projectId: azureus
clones:
  map: {}
