description: basic config with default colors and building representation
name: <80% crack coverage
building:
  padding: 0.2
  colors:
    faces: # ordered by importance, descending : in case of conflict, the first color to match will be displayed
      - name: "HOTSPOT"
        color: "#555555"
      - name: "VP"
        color: "#FF6F33"
      - name: "STRATEGY"
        color: "#17202a" # black
      - name: "FACTORY"
        color: "#7d3c98" # purple
      - name: "INTERFACE"
        color: "#e67e22" # orange
      - name: "ABSTRACT"
        color: "#2c3e50" # dark blue
      - name: "CLASS"
        color: "#335DFF"
      - name: "API"
      - name: "VARIANT"
      - name: "TEMPLATE"
      - name: "DECORATOR"
      - name: "COMPOSITION_STRATEGY"
      - name: "METHOD_LEVEL_VP"
      - name: "DENSE"
      - name: "PUBLIC"
      - name: "PRIVATE"
    edges:
      - name: "API"
        color: "#000000"
      - name: "HOTSPOT"
      - name: "VP"
      - name: "STRATEGY"
      - name: "FACTORY"
      - name: "INTERFACE"
      - name: "ABSTRACT"
      - name: "CLASS"
      - name: "VARIANT"
      - name: "TEMPLATE"
      - name: "DECORATOR"
      - name: "COMPOSITION_STRATEGY"
      - name: "METHOD_LEVEL_VP"
      - name: "DENSE"
      - name: "PUBLIC"
      - name: "PRIVATE"
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist:
  - org.jfree.chart.util.PublicCloneable
  - org.jfree.chart.event
  - org.jfree.data.general
api_classes:
  - org.jfree.chart.JFreeChart
  - org.jfree.chart.plot.Plot
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: complexity
  fade: ""
  crack: coverage
orientation: OUT
default_level: 4
camera_data:
  alpha: -0.0799982404701749
  beta: 0.9081976900356021
  radius: 55.31973277067907
  target:
    x: 17.220508054229995
    y: -2.544181127583636
    z: -4.262891364370626
metrics:
  complexity:
    min: 0
    max: 100
    higherIsBetter: false
  cognitive_complexity:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_lines:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_lines_density:
    min: 0
    max: 100
    higherIsBetter: false
  coverage:
    min: 0
    max: 80
    higherIsBetter: true
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
projectId: jfreechart-v1.5.0
clones:
  map: {}
