description: basic config with default colors and building representation
name: default config
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
    edges:
      - name: API
        color: "#000000"
    outlines: null
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - org.junit.Assert
  - org.junit.rules.TestRule
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: ""
  crack: ""
orientation: IN_OUT
default_level: 3
camera_data:
  alpha: 4.3140176433172615
  beta: 0.9904592921049088
  radius: 22.358675243028106
  target:
    x: 10.993009143123171
    y: 1.366910892105378
    z: 5.678720149333876
metrics:
  complexity:
    min: 0
    max: 100
    higherIsBetter: false
  cognitive_complexity:
    min: 0
    max: 100
    higherIsBetter: false
  coverage:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_lines:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_lines_density:
    min: 0
    max: 100
    higherIsBetter: false
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
projectId: junit-r4.12
