description: basic config with default colors and building representation
name: BeanComponentDefinition - AbstractBeanFactory
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
      - name: API
      - name: VARIANT
      - name: TEMPLATE
      - name: DECORATOR
      - name: COMPOSITION_STRATEGY
      - name: METHOD_LEVEL_VP
      - name: DENSE
      - name: PUBLIC
      - name: PRIVATE
    edges:
      - name: API
        color: "#000000"
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - org.springframework.beans.factory.parsing.BeanComponentDefinition
  - org.springframework.beans.factory.support.AbstractBeanFactory
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: ""
  crack: ""
orientation: IN
default_level: 8
camera_data:
  alpha: 0.376163656011301
  beta: 0.9518152051567018
  radius: 146.8119712444159
  target:
    x: 48.9543369833937
    y: -34.505661090962796
    z: 29.26107386660981
metrics:
  complexity:
    min: 0
    max: 25
    higherIsBetter: false
  cognitive_complexity:
    min: 0
    max: 150
    higherIsBetter: false
  duplicated_lines:
    min: 0
    max: 100
    higherIsBetter: false
  coverage:
    min: 0
    max: 100
    higherIsBetter: false
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
  ncloc:
    min: 0
    max: 100
    higherIsBetter: false
  bugs:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_blocks:
    min: 0
    max: 100
    higherIsBetter: false
projectId: spring
clones:
  map: {}
