description: basic config with default colors and building representation
name: VariMetrics view - Figure 5b
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
      - name: API
      - name: VARIANT
      - name: TEMPLATE
      - name: DECORATOR
      - name: COMPOSITION_STRATEGY
      - name: METHOD_LEVEL_VP
      - name: DENSE
      - name: PUBLIC
      - name: PRIVATE
    edges:
      - name: API
        color: "#000000"
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - org.jfree.chart.JFreeChart
  - org.jfree.chart.plot.Plot
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: coverage
  crack: duplicated_blocks
orientation: OUT
default_level: 4
camera_data:
  alpha: -19.235874922658315
  beta: 1.3896190244714275
  radius: 9.675523225664135
  target:
    x: 17.967490822791206
    y: 5.444169068621606
    z: -20.540815857989294
metrics:
  complexity:
    min: 0
    max: 25
    higherIsBetter: false
  cognitive_complexity:
    min: 0
    max: 150
    higherIsBetter: false
  duplicated_lines:
    min: 0
    max: 100
    higherIsBetter: false
  coverage:
    min: 0
    max: 100
    higherIsBetter: true
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
  ncloc:
    min: 0
    max: 100
    higherIsBetter: false
  bugs:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_blocks:
    min: 0
    max: 50
    higherIsBetter: false
projectId: jfreechart-refactored
clones:
  map: {}
