
projectName: "denislilajFox_jfreechart"
sourceCodePath: "source code path for local analysis"

sources:
- name: "sonarcloud"
  enabled: true
  commands:
  - "cmd 1"
  - "cmd 2"
  sourceUrl: "https://sonarcloud.io"
  metrics:
  - "complexity"
  - "cognitive_complexity"
