junit-r4.12: #Project name
  sourceCodePath: "source code path for local analysis"
  sources:
    - name: "sonarqube"
      enabled: true
      sourceProjectName: "junit%3Ajunit"
      commands:
        - "cmd 1"
        - "cmd 2"
      rootUrl: "http://localhost:9000"
      metrics:
        - "complexity"
        - "cognitive_complexity"
        - "coverage"

    - name: "sonarcloud"
      enabled: true
      sourceProjectName: "pfc-test.sonar%3Ajunit4-4.13.2"
      commands:
        - "cmd 1"
        - "cmd 2"
      rootUrl: "https://sonarcloud.io"
      metrics:
        - "complexity"
        - "cognitive_complexity"

jfreechart:
  sourceCodePath: "source code path for local analysis"
  sources:
    - name: "sonarcloud"
      enabled: true
      sourceProjectName: "denislilajFox_jfreechart"
      commands:
        - "cmd 1"
        - "cmd 2"
      rootUrl: "https://sonarcloud.io"
      metrics:
        - "complexity"
        - "cognitive_complexity"