junit-r4.12: #Project name
  sourceCodePath: "source code path for local analysis"
  sources:
    - name: "sonarcloud"
      enabled: true
      # --- --- EXECUTION CONFIG --- --- #
      shellLocation: "powershell.exe"
      workingDirectory: "C:\\Users\\Anton van der Tuijn"
      commands:
        - "echo 'command 1'"
        - "echo 'command 2'"
      # --- --- API CONFIG --- --- #
      rootUrl: "https://sonarcloud.io"
      componentName: "pfc-test.sonar%3Ajunit4-4.13.2"
      metrics:
        - "complexity"
        - "cognitive_complexity"

jfreechart-v1.5.0:
  sourceCodePath: "source code path for local analysis"
  sources:
    - name: "sonarcloud"
      enabled: true
      # --- --- EXECUTION CONFIG --- --- #
      shellLocation: "powershell.exe"
      workingDirectory: "C:\\Users\\Anton van der Tuijn"
      commands:
        - "dir"
        - "echo example"
      # --- --- API CONFIG --- --- #
      rootUrl: "https://sonarcloud.io"
      componentName: "denislilajFox_jfreechart"
      metrics:
        - "complexity"
        - "cognitive_complexity"