junit-r4.12: #Project name
  source-code-path: "source code path for local analysis"
  sources:
    - name: "sonarcloud"
      enabled: true
      # --- --- EXECUTION CONFIG --- --- #
      shell-location: "powershell.exe"
      working-directory: "C:"
      commands:
        - "echo 'command 1'"
        - "echo 'command 2'"
      # --- --- API CONFIG --- --- #
      root-url: "https://sonarcloud.io"
      component-name: "pfc-test.sonar%3Ajunit4-4.13.2"
      metrics:
        - "complexity"
        - "cognitive_complexity"

jfreechart-v1.5.0:
  source-code-path: "source code path for local analysis"
  sources:
    - name: "sonarcloud"
      enabled: true
      # --- --- EXECUTION CONFIG --- --- #
      shell-location: "powershell.exe"
      working-directory: "C:"
      commands:
        - "dir"
        - "echo example"
      # --- --- API CONFIG --- --- #
      root-url: "https://sonarcloud.io"
      component-name: "denislilajFox_jfreechart"
      metrics:
        - "complexity"
        - "cognitive_complexity"