junit-r4.12: #Project name
  sourceCodePath: "source code path for local analysis"
  sources:
    - name: "sonarcloud"
      enabled: true
      componentName: "pfc-test.sonar%3Ajunit4-4.13.2"
      commands:
        - "cmd 1"
        - "cmd 2"
      rootUrl: "https://sonarcloud.io"
      metrics:
        - "complexity"
        - "cognitive_complexity"

jfreechart-v1.5.0:
  sourceCodePath: "source code path for local analysis"
  sources:
    - name: "sonarcloud"
      enabled: true
      componentName: "denislilajFox_jfreechart"
      commands:
        - "cmd 1"
        - "cmd 2"
      rootUrl: "https://sonarcloud.io"
      metrics:
        - "complexity"
        - "cognitive_complexity"