description: basic config with default colors and building representation
name: MapContent - SimpleFeatureSource
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
      - name: API
      - name: VARIANT
      - name: TEMPLATE
      - name: DECORATOR
      - name: COMPOSITION_STRATEGY
      - name: METHOD_LEVEL_VP
      - name: DENSE
      - name: PUBLIC
      - name: PRIVATE
    edges:
      - name: API
        color: "#000000"
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - org.geotools.map.MapContent
  - org.geotools.data.simple.SimpleFeatureSource
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: ""
  crack: ""
orientation: OUT
default_level: 4
camera_data:
  alpha: -3.7841192055379906
  beta: 1.1620929281382253
  radius: 67.93968806801277
  target:
    x: 16.349620558702384
    y: 3.4799693503653915
    z: 38.907015670952674
metrics:
  complexity:
    min: 0
    max: 25
    higherIsBetter: false
  cognitive_complexity:
    min: 0
    max: 150
    higherIsBetter: false
  duplicated_lines:
    min: 0
    max: 100
    higherIsBetter: false
  coverage:
    min: 0
    max: 100
    higherIsBetter: false
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
  bugs:
    min: 0
    max: 100
    higherIsBetter: false
  ncloc:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_blocks:
    min: 0
    max: 100
    higherIsBetter: false
projectId: geotools
clones:
  map: {}
