description: basic config with default colors and building representation
name: metrics
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
      - name: API
        color: "#555555"
      - name: VARIANT
        color: "#555555"
      - name: TEMPLATE
        color: "#555555"
      - name: DECORATOR
        color: "#555555"
      - name: COMPOSITION_STRATEGY
        color: "#555555"
      - name: METHOD_LEVEL_VP
        color: "#555555"
      - name: DENSE
        color: "#555555"
      - name: PUBLIC
        color: "#555555"
      - name: PRIVATE
        color: "#555555"
    edges:
      - name: API
        color: "#000000"
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - org.openapitools.codegen.languages.OpenAPIGenerator
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: coverage
  crack: cognitive_complexity
orientation: IN_OUT
default_level: 6
camera_data:
  alpha: 4.038195952080021
  beta: 1.0715924348831192
  radius: 22.67996559518421
  target:
    x: 15.327667776199881
    y: 4.812910057839867
    z: 1.9058240437169016
metrics:
  complexity:
    min: 0
    max: 100
    higherIsBetter: false
  cognitive_complexity:
    min: 0
    max: 150
    higherIsBetter: false
  duplicated_lines:
    min: 0
    max: 100
    higherIsBetter: false
  coverage:
    min: 0
    max: 100
    higherIsBetter: false
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
  ncloc:
    min: 0
    max: 100
    higherIsBetter: false
  duplicated_blocks:
    min: 0
    max: 40
    higherIsBetter: false
  bugs:
    min: 0
    max: 100
    higherIsBetter: false
projectId: openapi-generator
clones:
  map: {}
