description: basic config with default colors and building representation
name: cognitive config
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
      - name: API
      - name: VARIANT
      - name: TEMPLATE
      - name: DECORATOR
      - name: COMPOSITION_STRATEGY
      - name: METHOD_LEVEL_VP
      - name: DENSE
      - name: PUBLIC
      - name: PRIVATE
    edges:
      - name: API
        color: "#000000"
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: USAGE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - USAGE
hierarchy_links:
  - USAGE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - org.codelibs.nekohtml.ObjectFactory
  - org.codelibs.nekohtml.filters.DefaultFilter
variables:
  width: nbConstructorVariants
  height: cognitive_complexity
  intensity: ""
  fade: ""
  crack: ""
orientation: IN_OUT
default_level: 4
camera_data:
  alpha: 0.38983722461005116
  beta: 0.6274204242561244
  radius: 33.12033374470425
  target:
    x: -2.0225579963587985
    y: 30.272937978789486
    z: 14.137475317206759
metrics:
  complexity:
    min: 0
    max: 25
    higherIsBetter: false
  cognitive_complexity:
    min: 0
    max: 150
    higherIsBetter: false
  coverage:
    min: 0
    max: 100
    higherIsBetter: false
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
projectId: nekohtml-2.1.1
clones:
  map: {}
