description: basic config with default colors and building representation
name: default config
building:
  padding: 0.2
  colors:
    faces:
      - name: "!HOTSPOT"
        color: "#555555"
      - name: VP
        color: "#FF6F33"
      - name: STRATEGY
        color: "#17202a"
      - name: FACTORY
        color: "#7d3c98"
      - name: INTERFACE
        color: "#e67e22"
      - name: ABSTRACT
        color: "#2c3e50"
      - name: CLASS
        color: "#335DFF"
    edges:
      - name: API
        color: "#000000"
    outlines: null
district:
  padding: 0
  colors:
    faces:
      - name: PACKAGE
        color: "#801A2E"
      - name: VP
        color: "#1A8039"
link:
  colors:
    - name: IMPLEMENTS
      color: "#ef2222"
    - name: EXTENDS
      color: "#3f97ff"
    - name: DUPLICATES
      color: "#2B914A"
    - name: INSTANTIATE
      color: "#1A8039"
  display:
    air_traffic:
      - IMPLEMENTS
      - EXTENDS
    underground_road:
      - INSTANTIATE
hierarchy_links:
  - INSTANTIATE
  - IMPLEMENTS
  - EXTENDS
blacklist: []
api_classes:
  - org.zalando.riptide.Http
variables:
  width: nbConstructorVariants
  height: nbMethodVariants
  intensity: ""
  fade: ""
  crack: ""
orientation: IN_OUT
default_level: 6
camera_data:
  alpha: -0.2608139453365763
  beta: 1.0490009748752809
  radius: 10.995731864455369
  target:
    x: 12.569953183134603
    y: 5.061764011035998
    z: 6.155661977831504
metrics:
  nbMethodVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbAttributes:
    min: 0
    max: 100
    higherIsBetter: false
  nbConstructorVariants:
    min: 0
    max: 100
    higherIsBetter: false
  nbVariants:
    min: 0
    max: 100
    higherIsBetter: false
projectId: riptide-2.11.0
clones:
  map: {}
