sourcePackage: resources

experiences:
  junit:
    repositoryUrl: https://github.com/junit-team/junit4
    tagIds:
      - r4.12
      - r4.11
  jhipster:
    repositoryUrl: https://github.com/jhipster/jhipster
    commitIds:
      - ad1a84c659cffa67b9e36bf14a8ce0bca9d2cbc3
      - 6f1a52a4aabe99fb3d2310019f61555d4682e763

