#
# This file is part of symfinder.
#
# symfinder is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# symfinder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with symfinder. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2018-2021 Johann Mortara <johann.mortara@univ-cotedazur.fr>
# Copyright 2018-2021 Xhevahire Tërnava <t.xheva@gmail.com>
# Copyright 2018-2021 Philippe Collet <philippe.collet@univ-cotedazur.fr>
#

  
name: VariCity CI
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'
            cache: maven
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Building the docker images
        run: bash build-docker-images.sh
      - name: Test source fetcher clone method
        working-directory: ./symfinder
        run: mvn clean package -Dtest=SourceFetcherTest#cloneRepositoryTest -DfailIfNoTests=false
      - name: Install all modules
        working-directory: ./symfinder
        run: mvn clean install -DskipTests
      - name: Unit tests on symfinder-engine
        working-directory: ./symfinder/symfinder-engine
        run: mvn clean install
      - name: Test Whole Chain on Cookie Factory
        working-directory: ./symfinder/integration-tests/test-cookie-factory
        run: bash runtest.sh
      - name: Non Regression Test on Cookie Factory
        working-directory: ./symfinder/integration-tests/test-non-regression-cf
        run: bash runtest.sh
      - name: Test Possibility to Skip Symfinder #58
        working-directory: ./symfinder/integration-tests/test-skip-symfinder-engine
        run: bash runtest.sh
      - name: Test Symfinder CLi works in command line mode  #58
        working-directory: ./symfinder/integration-tests/test-symfinder-cli
        run: bash runtest.sh
      - name: Test with symfinder-cli and varicity-backend (front is not used)
        working-directory: ./tests
        run: bash start.sh

#  integration_tests:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Tests on sample projects
#        run: ./run_integration_tests.sh
#      - name: Acceptance tests on a pilot project
#        run: ./run_acceptance_tests.sh sat4j

  varicity_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Varicity unit tests
        working-directory: ./tests
        run: chmod +x ./run_varicity_unit_tests.sh && ./run_varicity_unit_tests.sh
#      - name: Varicity integration tests
#        run: chmod +x ./run_varicity_integration_tests.sh && ./run_varicity_integration_tests.sh
        
#  cross_check:
#    needs: [build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Cross check test between varicity and symfindercomp
#        run: chmod +x ./run_cross_check_tests.sh && ./run_cross_check_tests.sh
